/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tampilan;

import Kelas.User;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;

public class frameUser extends javax.swing.JFrame {

    /**
     * Creates new form frameUser
     */
    public frameUser() {
        initComponents();
        Load_table();
        reset();
    }
    void reset(){
        Tusername.setText(null);
        Temail.setText(null);
        Tpassword.setText(null);
        Tfullname.setText(null);
        Cstatus.setSelectedItem(null);
    }
    
    void Load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Username");
        model.addColumn("Email");
        model.addColumn("Full Name");
        model.addColumn("Status");
        
        try {
            User usr = new User();
            ResultSet result = usr.TampilUser();
            while (result.next()){
                String status = (result.getInt("UserStatus") == 1) ? "Active" : "Inactive";
                model.addRow(new Object[]{
                    result.getString("UserName"),
                    result.getString("UserEmail"),
                    result.getString("UserFullName"),
                    status
                });
            }
            Tabeluser.setModel(model);
        } catch (SQLException e) {
            System.out.println("Eror : " + e.getMessage());
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Tusername = new javax.swing.JTextField();
        Temail = new javax.swing.JTextField();
        Tpassword = new javax.swing.JTextField();
        Tfullname = new javax.swing.JTextField();
        Cstatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabeluser = new javax.swing.JTable();
        Btambah = new javax.swing.JButton();
        Bubah = new javax.swing.JButton();
        Bhapus = new javax.swing.JButton();
        Breset = new javax.swing.JButton();
        Bkembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TusernameActionPerformed(evt);
            }
        });
        jPanel1.add(Tusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 210, 30));

        Temail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemailActionPerformed(evt);
            }
        });
        jPanel1.add(Temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 133, 210, 30));

        Tpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Tpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 210, 30));

        Tfullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfullnameActionPerformed(evt);
            }
        });
        jPanel1.add(Tfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 210, 30));

        Cstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "In Active", " " }));
        Cstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CstatusActionPerformed(evt);
            }
        });
        jPanel1.add(Cstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 210, 30));

        Tabeluser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabeluser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabeluserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabeluser);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 94, 400, 260));

        Btambah.setBackground(new java.awt.Color(102, 102, 255));
        Btambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btambah.setForeground(new java.awt.Color(255, 255, 255));
        Btambah.setText("Tambah");
        Btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtambahActionPerformed(evt);
            }
        });
        jPanel1.add(Btambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, 30));

        Bubah.setBackground(new java.awt.Color(102, 102, 255));
        Bubah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bubah.setForeground(new java.awt.Color(255, 255, 255));
        Bubah.setText("Ubah");
        Bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BubahActionPerformed(evt);
            }
        });
        jPanel1.add(Bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, 30));

        Bhapus.setBackground(new java.awt.Color(102, 102, 255));
        Bhapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bhapus.setForeground(new java.awt.Color(255, 255, 255));
        Bhapus.setText("Hapus");
        Bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BhapusActionPerformed(evt);
            }
        });
        jPanel1.add(Bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, 30));

        Breset.setBackground(new java.awt.Color(102, 102, 255));
        Breset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Breset.setForeground(new java.awt.Color(255, 255, 255));
        Breset.setText("Reset");
        Breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BresetActionPerformed(evt);
            }
        });
        jPanel1.add(Breset, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, 30));

        Bkembali.setBackground(new java.awt.Color(102, 102, 255));
        Bkembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bkembali.setForeground(new java.awt.Color(255, 255, 255));
        Bkembali.setText("Kembali");
        Bkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BkembaliActionPerformed(evt);
            }
        });
        jPanel1.add(Bkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 80, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 95, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 111, 95, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 95, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fullname");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 95, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Status");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 95, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\redmi\\OneDrive\\Pictures\\3.png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BkembaliActionPerformed
        // TODO add your handling code here:
        new frameDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BkembaliActionPerformed

    private void BresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_BresetActionPerformed

    private void BhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BhapusActionPerformed
        // TODO add your handling code here:
        User usr = new User();
        usr.setUserName(Tusername.getText());
        usr.setUserEmail(Temail.getText());
        usr.setUserPassword(Tpassword.getText());
        usr.setUserFullName(Tfullname.getText());

        if (Cstatus.getSelectedItem()=="Active") {
            usr.setUserStatus(1);
        } else {
            usr.setUserStatus(0);
        }
        usr.HapusUser();
        Load_table();
        reset();
    }//GEN-LAST:event_BhapusActionPerformed

    private void BubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BubahActionPerformed
        // TODO add your handling code here:
        User usr = new User();
        usr.setUserName(Tusername.getText());
        usr.setUserEmail(Temail.getText());
        usr.setUserPassword(Tpassword.getText());
        usr.setUserFullName(Tfullname.getText());

        if (Cstatus.getSelectedItem()=="Active") {
            usr.setUserStatus(1);
        } else {
            usr.setUserStatus(0);
        }
        usr.UbahUser();
        Load_table();
        reset();
    }//GEN-LAST:event_BubahActionPerformed

    private void BtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtambahActionPerformed
        // TODO add your handling code here:
        User usr = new User();
        usr.setUserName(Tusername.getText());
        usr.setUserEmail(Temail.getText());
        usr.setUserPassword(Tpassword.getText());
        usr.setUserFullName(Tfullname.getText());

        if (Cstatus.getSelectedItem()=="Active") {
            usr.setUserStatus(1);
        } else {
            usr.setUserStatus(0);
        }
        usr.TambahUser();
        Load_table();
        reset();

    }//GEN-LAST:event_BtambahActionPerformed

    private void CstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CstatusActionPerformed

    private void TfullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfullnameActionPerformed

    private void TpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TpasswordActionPerformed

    private void TemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TemailActionPerformed

    private void TusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TusernameActionPerformed

    private void TabeluserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabeluserMouseClicked
        // TODO add your handling code here:
        int row = Tabeluser.getSelectedRow();
        
        if (row != -1){
            String username = Tabeluser.getValueAt(row, 0).toString();
            String UserEmail = Tabeluser.getValueAt(row, 1).toString();
            String UserFullName = Tabeluser.getValueAt(row, 2).toString();
            String Status = Tabeluser.getValueAt(row, 3).toString();
            
            Tusername.setText(username);
            Temail.setText(UserEmail);
            Tfullname.setText(UserFullName);
            
            if (Status.equals("1")|| Status.equalsIgnoreCase("Active")){
                Cstatus.setSelectedItem("Active");
            }else{
                Cstatus.setSelectedItem("Inactive");
            }
        }
    }//GEN-LAST:event_TabeluserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bhapus;
    private javax.swing.JButton Bkembali;
    private javax.swing.JButton Breset;
    private javax.swing.JButton Btambah;
    private javax.swing.JButton Bubah;
    private javax.swing.JComboBox<String> Cstatus;
    private javax.swing.JTable Tabeluser;
    private javax.swing.JTextField Temail;
    private javax.swing.JTextField Tfullname;
    private javax.swing.JTextField Tpassword;
    private javax.swing.JTextField Tusername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
