/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tampilan;

import Kelas.Category;
import Kelas.Product;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
        
public class frameProduct extends javax.swing.JFrame {

    /**
     * Creates new form frameProduct
     */
    public frameProduct() {
        initComponents();
        Load_table();
        reset();
        valueComboBox();
    }
    
      void autoID(){
        Product catID = new Product();
        ResultSet rsVar = catID.autoId();
        try {
            
            if (rsVar.next()) {
                int id = rsVar.getInt("ID") + 1;
                Tid.setText(String.valueOf(id));
            } else {
                Tid.setText("1");
            }
            
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Error : " + sQLException.getMessage());
        }
    }    
    
    void reset(){
        autoID();
        Tname.setText(null);
        Tid.setEditable(false);
        Tdescription.setText(null);
        Tprice.setText(null);
        Ccategory.setSelectedItem(null);
    }
    void Load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Username");
        model.addColumn("Category");
        model.addColumn("Deskripsi");
        model.addColumn("Price");
        
        try {
            Product prd = new Product();
            ResultSet result = prd.TampilProduct();
            while (result.next()){
                
                model.addRow(new Object[]{
                    result.getInt("ProductID"),
                    result.getString("ProductName"),
                    result.getString("categoryName"),
                    result.getString("ProductDescription"),
                    result.getInt("ProductPrice"),
                    
                });
            }
            Tabelproduct.setModel(model);
        } catch (SQLException e) {
            System.out.println("Eror : " + e.getMessage());
        }
        
    }
    void valueComboBox(){
        
        try {
            Category value = new Category();
            ResultSet rs = value.dataComboBox();

            while (rs.next()) {
                String data = rs.getString("categoryName");
                Ccategory.addItem(data);
            }

        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Error : " + sQLException.getMessage());
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Btambah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Tid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Tname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tprice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Tdescription = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Ccategory = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabelproduct = new javax.swing.JTable();
        Bubah = new javax.swing.JButton();
        Bhapus = new javax.swing.JButton();
        Breset = new javax.swing.JButton();
        Bkembali = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btambah.setBackground(new java.awt.Color(0, 51, 255));
        Btambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btambah.setForeground(new java.awt.Color(255, 255, 255));
        Btambah.setText("Tambah");
        Btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtambahActionPerformed(evt);
            }
        });
        jPanel1.add(Btambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 80, -1));

        Tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TidActionPerformed(evt);
            }
        });
        jPanel1.add(Tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 210, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 80, -1));

        Tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnameActionPerformed(evt);
            }
        });
        jPanel1.add(Tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 210, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Category");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 80, -1));

        Tprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TpriceActionPerformed(evt);
            }
        });
        jPanel1.add(Tprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 210, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descriptiom");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 80, -1));

        Tdescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TdescriptionActionPerformed(evt);
            }
        });
        jPanel1.add(Tdescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 210, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 80, -1));

        Ccategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CcategoryActionPerformed(evt);
            }
        });
        jPanel1.add(Ccategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 210, 30));

        Tabelproduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabelproduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelproductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabelproduct);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 94, 400, 260));

        Bubah.setBackground(new java.awt.Color(0, 51, 255));
        Bubah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bubah.setForeground(new java.awt.Color(255, 255, 255));
        Bubah.setText("Ubah");
        Bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BubahActionPerformed(evt);
            }
        });
        jPanel1.add(Bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, 30));

        Bhapus.setBackground(new java.awt.Color(0, 51, 255));
        Bhapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bhapus.setForeground(new java.awt.Color(255, 255, 255));
        Bhapus.setText("Hapus");
        Bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BhapusActionPerformed(evt);
            }
        });
        jPanel1.add(Bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, 30));

        Breset.setBackground(new java.awt.Color(0, 51, 255));
        Breset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Breset.setForeground(new java.awt.Color(255, 255, 255));
        Breset.setText("Reset");
        Breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BresetActionPerformed(evt);
            }
        });
        jPanel1.add(Breset, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, 30));

        Bkembali.setBackground(new java.awt.Color(0, 51, 255));
        Bkembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bkembali.setForeground(new java.awt.Color(255, 255, 255));
        Bkembali.setText("Kembali");
        Bkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BkembaliActionPerformed(evt);
            }
        });
        jPanel1.add(Bkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 80, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\redmi\\OneDrive\\Documents\\Pictures\\User.png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtambahActionPerformed
        // TODO add your handling code here:
        Product productTambah = new Product();
        Category categoryTambah = new Category();
        
        try {
            productTambah.setProductId(Integer.parseInt(Tid.getText()));
            productTambah.setProductName(Tname.getText());
            productTambah.setProductDescription(Tdescription.getText());
            productTambah.setProductPrice(Integer.parseInt(Tprice.getText()));
            
            categoryTambah.setCategoryname(Ccategory.getSelectedItem().toString());
            ResultSet rsVarCek = categoryTambah.konversi();
            
            if (rsVarCek.next()) {
                int id = rsVarCek.getInt("categoryId");
                productTambah.setProductCategory(id);
            }
           
            productTambah.TambahProduct();
            
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(null, "Error : " + numberFormatException.getMessage());
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Error : " + sQLException.getMessage());
        }
        
        reset();
        Load_table();
        
    }//GEN-LAST:event_BtambahActionPerformed

    private void TidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TidActionPerformed

    private void TnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnameActionPerformed

    private void TpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TpriceActionPerformed

    private void TdescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TdescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TdescriptionActionPerformed

    private void CcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CcategoryActionPerformed

    private void BubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BubahActionPerformed
        // TODO add your handling code here:
        Product productTambah = new Product();
        Category categoryTambah = new Category();
        
        try {
            productTambah.setProductId(Integer.parseInt(Tid.getText()));
            productTambah.setProductName(Tname.getText());
            productTambah.setProductDescription(Tdescription.getText());
            productTambah.setProductPrice(Integer.parseInt(Tprice.getText()));
            
            categoryTambah.setCategoryname(Ccategory.getSelectedItem().toString());
            ResultSet rsVarCek = categoryTambah.konversi();
            
            if (rsVarCek.next()) {
                int id = rsVarCek.getInt("categoryId");
                productTambah.setProductCategory(id);
            }
           
            productTambah.UbahProduct();
            
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(null, "Error : " + numberFormatException.getMessage());
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Error : " + sQLException.getMessage());
        }
        
        reset();
        Load_table();
    }//GEN-LAST:event_BubahActionPerformed

    private void BhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BhapusActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        Product prd = new Product();
        prd.setProductId(Integer.parseInt(Tid.getText()));
        prd.HapusProduct();
        Load_table();
        reset();
     
    }//GEN-LAST:event_BhapusActionPerformed

    private void BresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_BresetActionPerformed

    private void BkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BkembaliActionPerformed
        // TODO add your handling code here:
        new frameDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BkembaliActionPerformed

    private void TabelproductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelproductMouseClicked
        // TODO add your handling code here:
        int row = Tabelproduct.getSelectedRow();
        
        if (row != -1){
            String id = Tabelproduct.getValueAt(row, 0).toString();
            String name = Tabelproduct.getValueAt(row, 1).toString();
            String category = Tabelproduct.getValueAt(row, 2).toString();
            String description = Tabelproduct.getValueAt(row, 3).toString();
            String price = Tabelproduct.getValueAt(row, 4).toString();
            
            Tid.setText(id);
            Tname.setText(name);
            Tdescription.setText(description);
            Tprice.setText(price);
            
            if (category.equals("1")|| category.equalsIgnoreCase("Active")){
                Ccategory.setSelectedItem("Active");
            }else{
                Ccategory.setSelectedItem("Inactive");
            }
        }
    }//GEN-LAST:event_TabelproductMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bhapus;
    private javax.swing.JButton Bkembali;
    private javax.swing.JButton Breset;
    private javax.swing.JButton Btambah;
    private javax.swing.JButton Bubah;
    private javax.swing.JComboBox<String> Ccategory;
    private javax.swing.JTable Tabelproduct;
    private javax.swing.JTextField Tdescription;
    private javax.swing.JTextField Tid;
    private javax.swing.JTextField Tname;
    private javax.swing.JTextField Tprice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
