/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tampilan;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import Kelas.Category;
import javax.swing.JOptionPane;

public class frameCategory extends javax.swing.JFrame {

    /**
     * Creates new form frameCategory
     */
    public frameCategory() {
        initComponents();
        Load_table();
        reset();
    }
    
    void autoID(){
        Category catID = new Category();
        ResultSet rsVar = catID.autoID();
        try {
            
            if (rsVar.next()) {
                int id = rsVar.getInt("id") + 1;
                Tid.setText(String.valueOf(id));
            } else {
                Tid.setText("1");
            }
            
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Error : " + sQLException.getMessage());
        }
    }     
   
    
void reset(){
    autoID();
        Tid.setEditable(false);
        Tname.setText(null);
        Tid.setText(null);
    }
    
    void Load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("id");
        model.addColumn("name");
        try {
            Category ctg = new Category();
            ResultSet result = ctg.TampilCategory();
            while (result.next()){
                model.addRow(new Object[]{
                    result.getString("CategoryId"),
                    result.getString("CategoryName"),
                });
            }
            Tabelcategory.setModel(model);
        } catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabelcategory = new javax.swing.JTable();
        Btambah = new javax.swing.JButton();
        Bubah = new javax.swing.JButton();
        Bhapus = new javax.swing.JButton();
        Breset = new javax.swing.JButton();
        Bkembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Tname = new javax.swing.JTextField();
        Tid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabelcategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabelcategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelcategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabelcategory);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 152, 629, 210));

        Btambah.setBackground(new java.awt.Color(102, 102, 255));
        Btambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btambah.setForeground(new java.awt.Color(255, 255, 255));
        Btambah.setText("Tambah");
        Btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtambahActionPerformed(evt);
            }
        });
        jPanel1.add(Btambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 116, 117, 30));

        Bubah.setBackground(new java.awt.Color(102, 102, 255));
        Bubah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bubah.setForeground(new java.awt.Color(255, 255, 255));
        Bubah.setText("Ubah");
        Bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BubahActionPerformed(evt);
            }
        });
        jPanel1.add(Bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 116, 110, 30));

        Bhapus.setBackground(new java.awt.Color(102, 102, 255));
        Bhapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bhapus.setForeground(new java.awt.Color(255, 255, 255));
        Bhapus.setText("Hapus");
        Bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BhapusActionPerformed(evt);
            }
        });
        jPanel1.add(Bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 116, 110, 30));

        Breset.setBackground(new java.awt.Color(102, 102, 255));
        Breset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Breset.setForeground(new java.awt.Color(255, 255, 255));
        Breset.setText("Reset");
        Breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BresetActionPerformed(evt);
            }
        });
        jPanel1.add(Breset, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 116, 110, 30));

        Bkembali.setBackground(new java.awt.Color(102, 102, 255));
        Bkembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bkembali.setForeground(new java.awt.Color(255, 255, 255));
        Bkembali.setText("Kembali");
        Bkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BkembaliActionPerformed(evt);
            }
        });
        jPanel1.add(Bkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 116, 110, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 138, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 138, -1));

        Tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnameActionPerformed(evt);
            }
        });
        jPanel1.add(Tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 68, 366, 30));

        Tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TidActionPerformed(evt);
            }
        });
        jPanel1.add(Tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 68, 245, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\redmi\\OneDrive\\Documents\\Pictures\\Producttt.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtambahActionPerformed
        // TODO add your handling code here:
        Category ctg = new Category();
        ctg.setCategoryname(Tname.getText());
        ctg.TambahCategory();
        Load_table();
        reset();
    }//GEN-LAST:event_BtambahActionPerformed

    private void BubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BubahActionPerformed
        // TODO add your handling code here:
        Category ctg = new Category();
        ctg.setCategoryname(Tname.getText());
        ctg.setCategoryid(Integer.parseInt(Tid.getText()));
        ctg.UbahCategory();
        Load_table();
        reset();
    }//GEN-LAST:event_BubahActionPerformed

    private void BhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BhapusActionPerformed
        // TODO add your handling code here:
        Category ctg = new Category();
        ctg.setCategoryid(Integer.parseInt(Tid.getText()));
        ctg.HapusCategory();
        Load_table();
        reset();
       
    }//GEN-LAST:event_BhapusActionPerformed

    private void BresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BresetActionPerformed
        // TODO add your handling code here:
       reset();
    }//GEN-LAST:event_BresetActionPerformed

    private void BkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BkembaliActionPerformed
        // TODO add your handling code here:
        new frameDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BkembaliActionPerformed

    private void TnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnameActionPerformed

    private void TidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TidActionPerformed

    private void TabelcategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelcategoryMouseClicked
        // TODO add your handling code here:
        int row = Tabelcategory.getSelectedRow();
        
        if (row != -1){
            String id = Tabelcategory.getValueAt(row, 0).toString();
            String name = Tabelcategory.getValueAt(row, 1).toString();
            
            Tid.setText(id);
            Tname.setText(name);
 
        }
    }//GEN-LAST:event_TabelcategoryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameCategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bhapus;
    private javax.swing.JButton Bkembali;
    private javax.swing.JButton Breset;
    private javax.swing.JButton Btambah;
    private javax.swing.JButton Bubah;
    private javax.swing.JTable Tabelcategory;
    private javax.swing.JTextField Tid;
    private javax.swing.JTextField Tname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
