/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tampilan;
import Kelas.Sesion;
import Kelas.User;
/**
 *
 * @author Hiddd
 */
public class frameDashboard extends javax.swing.JFrame {

    /**
     * Creates new form frameDashboard
     */
    public frameDashboard() {
        initComponents();
        username.setText(Sesion.getUsername());
        email.setText(Sesion.getEmail());
        nama.setText(Sesion.getFullname());
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RL = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        RL1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Background = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mfile = new javax.swing.JMenu();
        Btnlogout = new javax.swing.JRadioButtonMenuItem();
        Muser = new javax.swing.JMenu();
        Mproduct = new javax.swing.JMenu();
        Mcategory = new javax.swing.JMenu();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("FRAME USER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 120, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Have a nice day, Bro!");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 150, -1));

        RL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RL.setForeground(new java.awt.Color(255, 255, 255));
        RL.setText("Riwayat Login :");
        getContentPane().add(RL, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 280, -1));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 390, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("FRAME PRODUCT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 130, 40));

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 390, 30));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 390, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("FRAME CATEGORY");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 130, 40));

        RL1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RL1.setForeground(new java.awt.Color(253, 253, 253));
        RL1.setText("@Crudoop 2025");
        getContentPane().add(RL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 100, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 360));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\redmi\\OneDrive\\Pictures\\Desain Ui CrudOop.gif")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 370));

        Mfile.setText("File");
        Mfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MfileActionPerformed(evt);
            }
        });

        Btnlogout.setSelected(true);
        Btnlogout.setText("Logout");
        Btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnlogoutActionPerformed(evt);
            }
        });
        Mfile.add(Btnlogout);

        jMenuBar1.add(Mfile);

        Muser.setText("User");
        Muser.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                MuserMenuSelected(evt);
            }
        });
        jMenuBar1.add(Muser);

        Mproduct.setText("Product");
        Mproduct.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                MproductMenuSelected(evt);
            }
        });
        jMenuBar1.add(Mproduct);

        Mcategory.setText("Category");
        Mcategory.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                McategoryMenuSelected(evt);
            }
        });
        jMenuBar1.add(Mcategory);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MuserMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MuserMenuSelected
        // TODO add your handling code here:
        dispose();
        new frameUser().setVisible(true);
    }//GEN-LAST:event_MuserMenuSelected

    private void BtnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnlogoutActionPerformed
        // TODO add your handling code here:
        User usr = new User();
        usr.logOut();
        dispose();
        
    }//GEN-LAST:event_BtnlogoutActionPerformed

    private void MproductMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MproductMenuSelected
        // TODO add your handling code here:
        dispose();
        new frameProduct().setVisible(true);
    }//GEN-LAST:event_MproductMenuSelected

    private void McategoryMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_McategoryMenuSelected
        // TODO add your handling code here:
        dispose();
        new frameCategory().setVisible(true);
    }//GEN-LAST:event_McategoryMenuSelected

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void MfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MfileActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JRadioButtonMenuItem Btnlogout;
    private javax.swing.JMenu Mcategory;
    private javax.swing.JMenu Mfile;
    private javax.swing.JMenu Mproduct;
    private javax.swing.JMenu Muser;
    private javax.swing.JLabel RL;
    private javax.swing.JLabel RL1;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
